import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { generateLessonContent, generateStudyNotes, LessonContent, StudyNotes } from "@/lib/api";
import ReactMarkdown from "react-markdown";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { useToast } from "@/hooks/use-toast";
import { 
  ArrowLeft, 
  PlayCircle, 
  BookOpen, 
  ExternalLink, 
  Lightbulb,
  Code,
  CheckCircle2,
  Youtube,
  FileText,
  Download,
  Loader2
} from "lucide-react";
import { cn } from "@/lib/utils";

const LessonView = () => {
  const { moduleId } = useParams<{ moduleId: string }>();
  const [lesson, setLesson] = useState<LessonContent | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generatingNotes, setGeneratingNotes] = useState(false);
  const { toast } = useToast();

  const generateMarkdownNotes = (notes: StudyNotes): string => {
    let markdown = `# ${notes.title}\n\n`;
    markdown += `> ${notes.overview}\n\n`;
    markdown += `---\n\n`;
    
    // Detailed Notes
    markdown += notes.detailed_notes + `\n\n`;
    
    // Key Takeaways
    markdown += `## 🎯 Key Takeaways\n\n`;
    notes.key_takeaways.forEach((takeaway, idx) => {
      markdown += `${idx + 1}. ${takeaway}\n`;
    });
    markdown += `\n`;
    
    // Practice Exercises
    markdown += `## 💪 Practice Exercises\n\n`;
    notes.practice_exercises.forEach((exercise, idx) => {
      markdown += `${idx + 1}. ${exercise}\n`;
    });
    markdown += `\n`;
    
    // Additional Resources
    markdown += `## 📚 Further Study\n\n`;
    notes.additional_resources.forEach((resource, idx) => {
      markdown += `- ${resource}\n`;
    });
    markdown += `\n`;
    
    // Sources
    if (notes.sources.length > 0) {
      markdown += `## 🔗 Sources\n\n`;
      notes.sources.forEach((source, idx) => {
        const icon = source.type === 'video' ? '🎥' : '📄';
        markdown += `${idx + 1}. ${icon} **${source.title}**\n`;
        markdown += `   - Link: [${source.url}](${source.url})\n\n`;
      });
    }
    
    // Footer
    markdown += `---\n\n`;
    markdown += `*Generated by AdaptEd - Your Personalized Learning Platform*\n`;
    markdown += `*Date: ${new Date().toLocaleDateString()}*\n`;
    
    return markdown;
  };

  const downloadStudyNotes = async () => {
    if (!lesson) return;
    
    try {
      setGeneratingNotes(true);
      toast({
        title: "Generating Study Notes...",
        description: "AI is creating comprehensive notes for you. This may take a moment.",
      });
      
      // Generate study notes from lesson
      const notes = await generateStudyNotes(lesson);
      
      // Convert to markdown
      const markdown = generateMarkdownNotes(notes);
      
      // Download
      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${lesson.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_study_notes.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Study Notes Downloaded!",
        description: "Your comprehensive study notes have been saved as a Markdown file.",
      });
    } catch (err) {
      console.error('Error generating notes:', err);
      toast({
        title: "Generation Failed",
        description: err instanceof Error ? err.message : "Failed to generate study notes",
        variant: "destructive",
      });
    } finally {
      setGeneratingNotes(false);
    }
  };

  const copyStudyNotesToClipboard = async () => {
    if (!lesson) return;
    
    try {
      setGeneratingNotes(true);
      toast({
        title: "Generating Study Notes...",
        description: "AI is creating comprehensive notes for you. This may take a moment.",
      });
      
      // Generate study notes from lesson
      const notes = await generateStudyNotes(lesson);
      
      // Convert to markdown
      const markdown = generateMarkdownNotes(notes);
      
      // Copy to clipboard
      await navigator.clipboard.writeText(markdown);
      
      toast({
        title: "Copied to Clipboard!",
        description: "You can now paste the comprehensive study notes into Notion or any other app.",
      });
    } catch (err) {
      console.error('Error generating notes:', err);
      toast({
        title: "Generation Failed",
        description: err instanceof Error ? err.message : "Failed to generate study notes",
        variant: "destructive",
      });
    } finally {
      setGeneratingNotes(false);
    }
  };

  useEffect(() => {
    let cancelled = false;
    
    const loadLesson = async () => {
      if (!moduleId) return;

      try {
        setLoading(true);
        setError(null);
        
        // Decode the module title from the URL
        const moduleTopic = decodeURIComponent(moduleId);
        console.log('Loading lesson for topic:', moduleTopic);
        
        // Check if lesson is cached in localStorage
        const cacheKey = `lesson_${moduleTopic}`;
        const cachedLesson = localStorage.getItem(cacheKey);
        
        if (cachedLesson) {
          console.log('✓ Loading lesson from cache');
          const lessonData = JSON.parse(cachedLesson);
          if (!cancelled) {
            setLesson(lessonData);
            setLoading(false);
          }
          return;
        }
        
        console.log('No cache found, fetching from API...');
        
        // Fetch lesson content from API
        const lessonData = await generateLessonContent({
          topic: moduleTopic,
          user_preference: "visual", // You can make this dynamic based on user settings
        });
        
        // Only update state if not cancelled
        if (!cancelled) {
          console.log('Lesson data received:', lessonData);
          
          // Cache the lesson in localStorage
          try {
            localStorage.setItem(cacheKey, JSON.stringify(lessonData));
            console.log('✓ Lesson cached in localStorage');
          } catch (storageErr) {
            console.warn('Failed to cache lesson:', storageErr);
          }
          
          console.log('Setting lesson state...');
          setLesson(lessonData);
          console.log('✓ Lesson loaded successfully');
        }
      } catch (err) {
        // Only update state if not cancelled
        if (!cancelled) {
          const errorMessage = err instanceof Error ? err.message : "Failed to load lesson";
          console.error('Error loading lesson:', err);
          console.error('Error message:', errorMessage);
          setError(errorMessage);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };

    loadLesson();
    
    // Cleanup function to prevent state updates after unmount
    return () => {
      cancelled = true;
    };
  }, [moduleId]);

  if (loading) {
    return (
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="flex items-center justify-center h-96">
          <div className="text-center space-y-4">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
            <p className="text-muted-foreground">Generating your personalized lesson...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error || !lesson) {
    return (
      <div className="max-w-5xl mx-auto space-y-6">
        <Link to="/learning-path">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Learning Path
          </Button>
        </Link>
        <Card className="border-destructive">
          <CardContent className="pt-6">
            <div className="text-center space-y-2">
              <p className="text-destructive font-medium">Error loading lesson</p>
              <p className="text-sm text-muted-foreground">{error}</p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-4"
      >
        <Link to="/learning-path">
          <Button variant="ghost" size="sm">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Learning Path
          </Button>
        </Link>

        <div className="flex items-start justify-between gap-4">
          <div className="space-y-2 flex-1">
            <h1 className="text-3xl font-bold text-foreground">{lesson.title}</h1>
            <p className="text-muted-foreground">{lesson.summary}</p>
          </div>
          
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={copyStudyNotesToClipboard}
              disabled={generatingNotes}
              className="gap-2"
            >
              {generatingNotes ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4" />
                  Copy Notes
                </>
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={downloadStudyNotes}
              disabled={generatingNotes}
              className="gap-2"
            >
              {generatingNotes ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  Download
                </>
              )}
            </Button>
          </div>
        </div>
      </motion.div>

      {/* Key Concepts */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <Lightbulb className="w-5 h-5 text-primary" />
              Key Concepts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {lesson.key_concepts.map((concept, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-success mt-0.5 shrink-0" />
                  <span className="text-sm">{concept}</span>
                  {lesson.citation_map && lesson.citation_map[concept] !== undefined && (
                    <Badge variant="outline" className="ml-2 text-xs">
                      Source {lesson.citation_map[concept] + 1}
                    </Badge>
                  )}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </motion.div>

      {/* Main Content */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <BookOpen className="w-5 h-5 text-primary" />
              Lesson Content
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown
                components={{
                  code({ node, inline, className, children, ...props }) {
                    const match = /language-(\w+)/.exec(className || "");
                    return !inline && match ? (
                      <SyntaxHighlighter
                        style={vscDarkPlus}
                        language={match[1]}
                        PreTag="div"
                        {...props}
                      >
                        {String(children).replace(/\n$/, "")}
                      </SyntaxHighlighter>
                    ) : (
                      <code className={className} {...props}>
                        {children}
                      </code>
                    );
                  },
                }}
              >
                {lesson.main_content}
              </ReactMarkdown>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Code Snippets */}
      {lesson.code_snippets.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Code className="w-5 h-5 text-primary" />
                Code Examples
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {lesson.code_snippets.map((snippet, idx) => (
                <div key={idx} className="space-y-2">
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary">{snippet.language}</Badge>
                  </div>
                  <SyntaxHighlighter
                    style={vscDarkPlus}
                    language={snippet.language}
                    PreTag="div"
                    customStyle={{ borderRadius: "0.5rem" }}
                  >
                    {snippet.code}
                  </SyntaxHighlighter>
                </div>
              ))}
            </CardContent>
          </Card>
        </motion.div>
      )}

      {/* Quiz Question */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
      >
        <Card className="border-primary/30 bg-primary/5">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <Lightbulb className="w-5 h-5 text-primary" />
              Quick Check
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm font-medium">{lesson.quiz_question}</p>
          </CardContent>
        </Card>
      </motion.div>

      {/* Sources */}
      {lesson.sources.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <ExternalLink className="w-5 h-5 text-primary" />
                Sources
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {lesson.sources.map((source, idx) => (
                  <a
                    key={idx}
                    href={source.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-start gap-3 p-3 rounded-lg border hover:bg-accent transition-colors group"
                  >
                    <div className={cn(
                      "w-10 h-10 rounded-lg flex items-center justify-center shrink-0",
                      source.type === "video" ? "bg-red-500/10" : "bg-blue-500/10"
                    )}>
                      {source.type === "video" ? (
                        <Youtube className="w-5 h-5 text-red-500" />
                      ) : (
                        <FileText className="w-5 h-5 text-blue-500" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <Badge variant="outline" className="text-xs">
                          Source {idx + 1}
                        </Badge>
                        <Badge variant="secondary" className="text-xs">
                          {source.type}
                        </Badge>
                        {source.metadata?.views && source.metadata.views !== 'N/A' && (
                          <Badge variant="outline" className="text-xs text-muted-foreground">
                            {source.metadata.views}
                          </Badge>
                        )}
                      </div>
                      <p className="font-medium text-sm mt-1 group-hover:text-primary transition-colors">
                        {source.title}
                      </p>
                      <p className="text-xs text-muted-foreground truncate mt-0.5">
                        {source.url}
                      </p>
                    </div>
                    <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors shrink-0" />
                  </a>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      )}

      <Separator />

      {/* Action Buttons */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
        className="flex items-center justify-between"
      >
        <div className="flex items-center gap-2">
          <Link to="/learning-path">
            <Button variant="outline">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Learning Path
            </Button>
          </Link>
          <Button 
            variant="ghost" 
            size="sm"
            onClick={() => {
              const cacheKey = `lesson_${decodeURIComponent(moduleId || '')}`;
              localStorage.removeItem(cacheKey);
              window.location.reload();
            }}
            className="text-xs text-muted-foreground"
          >
            Refresh Lesson
          </Button>
        </div>
        <Button 
          size="lg" 
          className="gap-2" 
          disabled={!lesson}
          onClick={() => {
            // Navigate to Viva with module info
            const vivaUrl = `/viva/${encodeURIComponent(moduleId || '')}?moduleTitle=${encodeURIComponent(lesson.title)}&moduleDescription=${encodeURIComponent(lesson.summary)}`;
            window.location.href = vivaUrl;
          }}
        >
          <PlayCircle className="w-5 h-5" />
          Start Viva
        </Button>
      </motion.div>
    </div>
  );
};

export default LessonView;
